# GitHub 라벨 정의
# 이 파일을 사용하려면 github-label-sync 같은 도구를 사용하거나
# 아래 정의를 참고해서 GitHub UI에서 수동으로 생성하세요.

# 이슈 타입
- name: bug
  color: d73a4a
  description: 버그나 오류

- name: enhancement
  color: a2eeef
  description: 새로운 기능이나 개선사항

- name: refactor
  color: fbca04
  description: 코드 리팩토링

- name: chore
  color: fef2c0
  description: 빌드, 설정 등 기타 작업

- name: test
  color: 1d76db
  description: 테스트 추가 또는 수정

- name: style
  color: c5def5
  description: 코드 포맷팅, 세미콜론 등

- name: documentation
  color: 0075ca
  description: 문서 개선

- name: question
  color: d876e3
  description: 추가 정보나 명확화가 필요함

# 상태
- name: duplicate
  color: cfd3d7
  description: 중복된 이슈나 PR

- name: invalid
  color: e4e669
  description: 유효하지 않은 내용

- name: wontfix
  color: ffffff
  description: 수정하지 않을 예정

# 우선순위/난이도
- name: good first issue
  color: 7057ff
  description: 초보자에게 좋은 이슈

- name: help wanted
  color: 008672
  description: 도움이 필요함

- name: priority:high
  color: b60205
  description: 높은 우선순위

- name: priority:low
  color: e99695
  description: 낮은 우선순위
